version: "3.9"

services:
  bd:
    container_name: postgres_bd
    image: postgres:14.5
    hostname: postgres
    restart: always
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=aleks
      - POSTGRES_DB=clinic
